server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/travel
    username: postgres
    password: postgres
  jpa:
    show-sql: false
springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
jwt:
  secret: 2dfe2sd45xqe34z9je4
  duration: 15
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
info:
  application:
    name: traveldiary
    description: Travel diary, spring boot application
    version: 0.0.1-SNAPSHOT
